#!/usr/bin/env bash
# E15a / H22a: run three php-src suites through the Ignis binary and compare with the stock CLI.
#
#   mode "stock"  -> TEST_PHP_EXECUTABLE=/opt/php85-zts/bin/php        (same libphp build, cli SAPI)
#   mode "main"   -> scripts/ignis-php                                  (test runs in {main} of the embed)
#   mode "fiber"  -> scripts/ignis-php with IGNIS_PHPT_MODE=fiber       (test body runs inside an Ignis fiber)
#
# Results: bench/results/e15-phpt/<mode>-<suite>.txt   (failing test names, one per line)
#          bench/results/e15-phpt/<mode>-<suite>.log   (full run-tests output incl. --show-diff)
#          bench/results/e15-phpt/<mode>-<suite>.tsv   (RESULT<TAB>test for every test)
#          bench/results/e15-phpt/<mode>-diffs/...     (the .diff/.out run-tests wrote next to each test)
#          bench/results/e15-phpt/summary.md           (counts table)
set -uo pipefail
cd "$(dirname "$0")/.."
ROOT=$PWD
PHPSRC=${PHPSRC:-/home/user/php-src}
STOCK=${STOCK:-/opt/php85-zts/bin/php}
OUT=$ROOT/bench/results/e15-phpt
SUITE_TIMEOUT=${SUITE_TIMEOUT:-1200}     # 20 min cap per suite run
TEST_TIMEOUT=${TEST_TIMEOUT:-15}         # per-test timeout handed to run-tests (--set-timeout)

SUITES=(Zend/tests/fibers ext/standard/tests/streams ext/sockets/tests)
MODES=(stock main fiber)

mkdir -p "$OUT"
: > "$OUT/summary.tsv"

clean_tree() {
  # ONLY the three suite directories are cleaned; nothing else in php-src is touched.
  git -C "$PHPSRC" clean -fdq -- Zend/tests/fibers ext/standard/tests/streams ext/sockets/tests
  # bug60106-00{1,2} bind a unix socket at /tmp/<107 x "a"> and only unlink it if they pass;
  # a leftover from a failed run makes the NEXT run fail with EADDRINUSE, in every mode.
  rm -f /tmp/aaaaaaaaaaaaaaaaaaaa* 2>/dev/null
}

collect_artifacts() { # mode suite
  local mode=$1 suite=$2 dest="$OUT/$1-diffs"
  local f rel
  while IFS= read -r -d '' f; do
    rel=${f#"$PHPSRC"/}
    mkdir -p "$dest/$(dirname "$rel")"
    cp -f "$f" "$dest/$rel"
  done < <(find "$PHPSRC/$suite" \( -name '*.diff' -o -name '*.out' \) -print0 2>/dev/null)
}

run_suite() { # mode suite
  local mode=$1 suite=$2
  local tag="$mode-$(echo "$suite" | tr '/' '_')"
  local exe="$ROOT/scripts/ignis-php"
  [ "$mode" = stock ] && exe=$STOCK

  clean_tree
  echo "=== $mode :: $suite ==="
  local t0 t1
  t0=$(date +%s%N)
  (
    [ "$mode" = fiber ] && export IGNIS_PHPT_MODE=fiber
    cd "$PHPSRC"
    # -q: no interactive prompt; --offline: never touch an external host; --show-diff: diffs in the log;
    # -w/-W: machine-readable failing / all results; --set-timeout: per-test wall clock.
    timeout "$SUITE_TIMEOUT" "$STOCK" "$PHPSRC/run-tests.php" \
      -q --offline --no-color --show-diff \
      --set-timeout "$TEST_TIMEOUT" \
      -p "$exe" \
      -w "$OUT/$tag.txt" -W "$OUT/$tag.tsv" \
      "$PHPSRC/$suite"
  ) > "$OUT/$tag.log" 2>&1
  local rc=$?
  t1=$(date +%s%N)
  local secs=$(( (t1 - t0) / 1000000000 ))

  collect_artifacts "$mode" "$suite"
  clean_tree

  local total pass fail skip warn bork
  total=$(grep -m1 '^Number of tests' "$OUT/$tag.log" | awk '{print $5}')
  pass=$( grep -m1 '^Tests passed'    "$OUT/$tag.log" | awk '{print $4}')
  fail=$( grep -m1 '^Tests failed'    "$OUT/$tag.log" | awk '{print $4}')
  skip=$( grep -m1 '^Tests skipped'   "$OUT/$tag.log" | awk '{print $4}')
  warn=$( grep -m1 '^Tests warned'    "$OUT/$tag.log" | awk '{print $4}')
  bork=$( grep -m1 '^Tests borked'    "$OUT/$tag.log" | awk '{print $4}')
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$mode" "$suite" "${total:-?}" "${pass:-0}" "${fail:-0}" "${skip:-0}" "${warn:-0}" "${bork:-0}" "$secs" \
    | tee -a "$OUT/summary.tsv"
  [ $rc -eq 124 ] && echo "  !! suite hit the ${SUITE_TIMEOUT}s cap"
}

for suite in "${SUITES[@]}"; do
  for mode in "${MODES[@]}"; do
    run_suite "$mode" "$suite"
  done
done

{
  echo "# E15a — php-src suites under Ignis (generated by bench/e15-phpt.sh)"
  echo
  echo "| suite | mode | total | passed | failed | skipped | warned | borked | wall s |"
  echo "|---|---|---:|---:|---:|---:|---:|---:|---:|"
  sort -t"$(printf '\t')" -k2,2 -k1,1r "$OUT/summary.tsv" | while IFS=$'\t' read -r m s t p f k w b sec; do
    echo "| $s | $m | $t | $p | $f | $k | $w | $b | $sec |"
  done
} > "$OUT/summary.md"
cat "$OUT/summary.md"
