[package]
name = "temporal-probe"
version = "0.0.1"
edition = "2024"

[dependencies]
temporalio-sdk-core = { git = "https://github.com/temporalio/sdk-core" }
temporalio-common = { git = "https://github.com/temporalio/sdk-core" }
temporalio-protos = { git = "https://github.com/temporalio/sdk-core" }
temporalio-client = { git = "https://github.com/temporalio/sdk-core" }
tokio = { version = "1", features = ["full"] }
url = "2"
